[workspace]
git_release_enable = true
changelog_update = true
pr_labels = ["release"]

[[package]]
name = "ankit"

[[package]]
name = "ankit-engine"

[[package]]
name = "ankit-mcp"

[[package]]
name = "ankit-builder"
