[book]
title = "Ankit Documentation"
authors = ["Josh Rotenberg"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/joshrotenberg/ankit"
edit-url-template = "https://github.com/joshrotenberg/ankit/edit/main/docs/{path}"
site-url = "/ankit/"
default-theme = "light"
preferred-dark-theme = "navy"

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false
copyable = true
